name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: MY_WEBAPP_NAME   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'             # set this to the .NET Core version to use

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET Core SDK ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore
        run: dotnet restore
             
      - name: Build app
        run: dotnet build -c Release --no-restore 
      
     # - name: Publish
      #  run: dotnet publish --no-build -c Release -o ./Published
